# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: "/hackdata"

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://acm-snu.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "isthegeek"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "HackData | 7/8 October 2017"
  description: "Coming Soon!"
  image:       "https://i.imgur.com/o9A9mhJ.png"

# Event information.
event:
  name:        "HackData"
  description: "Coming Soon!"
  date:        "7 & 8 October 2017"
  location:    "Shiv Nadar University"


  about:
    description: >
      This interdisciplinary & experiential event is open-ended and meant to bring together engineers, business students, designers, entrepreneurs, etc. Utilize data science in useful and positive ways beyond the classroom and Kaggle competitions.


  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending a hackathon is free.
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "How many people can be in a Team?"
      answer: >
        You can form teams of upto 3 members.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at Shiv Nadar University.
    - question: "How to get to HackData?"
      answer: >
        We will be providing several busses from Sector-16 Metro station, Noida. We'll confirm the timing soon.
    - question: "What should I bring?"
      answer: >
        Laptop, Charger, Change of clothes and a Cool Hack idea. Don't worry about food or drinks, we've got you covered there.
    - question: "What if I have never been to a Hackathon before?"
      answer: >
        No worries! Hackathons can be a great place to learn a lot new skills. You will meet lots of awesome people where, Just come eager to learn and build.



  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
